.PHONY: chat_serv chat_cli news_serv news_cli clean

chatServ:
	@echo "Ejecutando servidor de chat..."
	@python3 chat/serv7_chat.py

chatCli:
	@echo "Ejecutando cliente de chat..."
	@python3 chat/cli7_chat.py

newsServ:
	@echo "Ejecutando servidor de noticias..."
	@python3 news/serv7_news.py

newsCli:
	@echo "Ejecutando cliente de noticias..."
	@python3 news/cli7_news.py

clean:
	@echo "Limpiando..."
	@rm -rf __pycache__
