# Makefile para la aplicación Cliente-Servidor mediante FIFOs

# Application1: Ejecutar el servidor y cliente para el contenido del archivo
runApp1Serv:
	@echo "Iniciando el servidor para la aplicación de contenido de archivo..."
	@python3 application1/serv3.py

runApp1Cli:
	@echo "Iniciando el cliente para la aplicación de contenido de archivo..."
	@python3 application1/cli3.py application1/hola.txt

# Application2: Ejecutar el servidor y cliente para la fecha y hora
runApp2Serv:
	@echo "Iniciando el servidor para la aplicación de fecha y hora..."
	@python3 application2/serv3.py

runApp2Cli:
	@echo "Iniciando el cliente para la aplicación de fecha y hora..."
	@python3 application2/cli3.py

all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."
