runApp1:
	@echo "Ejecutando el script de cliente-servidor para leer fichero 'hola.txt'."
	@python3 application1/cliserv2.py application1/hola.txt

runApp2:
	@echo "Ejecutando el servidor y cliente de fecha y hora."
	@python3 application2/cliserv2.py

all: runApp1 runApp2
	@echo "Compilación y ejecución de la práctica completada."
	
clean:
	@echo "Limpiando..."