# Makefile para compilar y ejecutar cada aplicación

runApp1Serv:
	@echo "Ejecutando el servidor de App1..."
	@python3 app1/serv5.py

runApp1Cli:
	@echo "Ejecutando el cliente de App1..."
	@python3 app1/cli5.py

runApp2Serv:
	@echo "Ejecutando el servidor de App2..."
	@python3 app2/serv5.py

runApp2Cli:
	@echo "Ejecutando el cliente de App2..."
	@python3 app2/cli5.py

clean:
	@echo "Limpiando..."
	rm -rf __pycache__